# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftWeb3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'web3.swift.pod'
  # Pods for SwiftWeb3

end
